type R2Object={body:ReadableStream;httpMetadata?:{contentType?:string}};
type R2Bucket={put:(key:string,value:ArrayBuffer,options?:{httpMetadata?:{contentType?:string}})=>Promise<unknown>;get:(key:string)=>Promise<R2Object|null>;delete:(key:string)=>Promise<void>};
const key=(eventId:number)=>`archive-results/${eventId}.pdf`;
async function bucket():Promise<R2Bucket|null>{if(process.env.RAILWAY_ENVIRONMENT||process.env.DATABASE_PATH)return null;const moduleName="cloudflare:workers";const runtime=await import(moduleName) as unknown as{env?:{ARCHIVE_PDFS?:R2Bucket}};return runtime.env?.ARCHIVE_PDFS??null}
async function localPath(eventId:number){const fsName="node:fs",pathName="node:path";const[{mkdirSync},path]=await Promise.all([import(fsName),import(pathName)]);const root=process.env.DATABASE_PATH?path.dirname(process.env.DATABASE_PATH):".wrangler";const directory=path.join(root,"archive-pdfs");mkdirSync(directory,{recursive:true});return path.join(directory,`${eventId}.pdf`)}
export async function putArchivePdf(eventId:number,data:ArrayBuffer){const b=await bucket();if(b){await b.put(key(eventId),data,{httpMetadata:{contentType:"application/pdf"}});return}const fsName="node:fs/promises";const fs=await import(fsName);await fs.writeFile(await localPath(eventId),new Uint8Array(data))}
export async function getArchivePdf(eventId:number):Promise<{body:unknown;contentType:string}|null>{const b=await bucket();if(b){const object=await b.get(key(eventId));return object?{body:object.body,contentType:object.httpMetadata?.contentType||"application/pdf"}:null}try{const fsName="node:fs/promises";const fs=await import(fsName);return{body:await fs.readFile(await localPath(eventId)),contentType:"application/pdf"}}catch{return null}}
export async function deleteArchivePdf(eventId:number){const b=await bucket();if(b){await b.delete(key(eventId));return}try{const fsName="node:fs/promises";const fs=await import(fsName);await fs.unlink(await localPath(eventId))}catch{}}
export async function putStartListRtf(id:number,data:ArrayBuffer){const b=await bucket();if(b){await b.put(`start-lists/${id}.rtf`,data,{httpMetadata:{contentType:"application/rtf"}});return}const fsName="node:fs/promises",pathName="node:path";const[fs,path]=await Promise.all([import(fsName),import(pathName)]);const pdfPath=await localPath(id);const target=path.join(path.dirname(path.dirname(pdfPath)),"start-lists",`${id}.rtf`);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,new Uint8Array(data))}
export async function deleteStartListRtf(id:number){const b=await bucket();if(b){await b.delete(`start-lists/${id}.rtf`);return}try{const fsName="node:fs/promises",pathName="node:path";const[fs,path]=await Promise.all([import(fsName),import(pathName)]);const pdfPath=await localPath(id);await fs.unlink(path.join(path.dirname(path.dirname(pdfPath)),"start-lists",`${id}.rtf`))}catch{}}
