export type Result={id:number;athlete:string;club:string;time:string;points:number;status:string};
export type BracketSlot={round:number;position:number;athlete:string};
export type Bracket={size:number;slots:BracketSlot[]};
export type EventData={id:number;title:string;category:string;location:string;eventDate:string;isLive:number|boolean;nextStart:string|null;updatedAt:string;results:Result[];bracket?:Bracket};
const seed:EventData[]=[{id:1,title:"5-Buoy Course",category:"Senior · Open",location:"Gyékényes",eventDate:"2026-08-20",isLive:1,nextStart:"14:32",updatedAt:new Date().toISOString(),results:[{id:1,athlete:"Kovács Luca",club:"Muréna SE",time:"04:18",points:1000,status:"Finished"},{id:2,athlete:"Nagy Bence",club:"Debreceni Búvárklub",time:"04:23",points:978,status:"Finished"}]},{id:2,title:"Star Course",category:"Senior · Women",location:"Gyékényes",eventDate:"2026-08-19",isLive:0,nextStart:null,updatedAt:"2026-08-19T16:20:00Z",results:[]}];
type Statement={bind:(...v:unknown[])=>Statement;run:()=>Promise<{meta?:{last_row_id?:number}}> ;all:<T>()=>Promise<{results:T[]}>};type D1={prepare:(sql:string)=>Statement;batch:(s:Statement[])=>Promise<unknown>};
let railwayDb:D1|null=null;
async function db():Promise<D1|null>{
  if(process.env.RAILWAY_ENVIRONMENT||process.env.DATABASE_PATH){
    if(railwayDb)return railwayDb;
    const sqliteModule="node:sqlite",fsModule="node:fs",pathModule="node:path";
    const[{DatabaseSync},{mkdirSync},path]=await Promise.all([import(sqliteModule),import(fsModule),import(pathModule)]);
    const file=process.env.DATABASE_PATH||".wrangler/railway.db";mkdirSync(path.dirname(file),{recursive:true});const native=new DatabaseSync(file);native.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");
    const prepare=(sql:string):Statement=>{let values:unknown[]=[];const api:Statement={bind:(...v:unknown[])=>{values=v;return api},run:async()=>{const result=native.prepare(sql).run(...values);return{meta:{last_row_id:Number(result.lastInsertRowid||0)}}},all:async<T>()=>({results:native.prepare(sql).all(...values) as T[]})};return api};
    railwayDb={prepare,batch:async(statements:Statement[])=>{for(const statement of statements)await statement.run()}};return railwayDb;
  }
  const cloudflareModule="cloudflare:workers";const runtime=await import(cloudflareModule) as unknown as {env?:{DB?:D1}};return runtime.env?.DB??null;
}
export async function ensureDb(){const d=await db();if(!d)return null;await d.batch([
  d.prepare("CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, category TEXT NOT NULL, location TEXT NOT NULL, event_date TEXT NOT NULL, is_live INTEGER NOT NULL DEFAULT 0, next_start TEXT, updated_at TEXT NOT NULL)"),
  d.prepare("CREATE TABLE IF NOT EXISTS results (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE, athlete TEXT NOT NULL, club TEXT NOT NULL, time TEXT NOT NULL, points INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'Finished')"),
  d.prepare("CREATE TABLE IF NOT EXISTS parallel_brackets (event_id INTEGER PRIMARY KEY REFERENCES events(id) ON DELETE CASCADE, bracket_size INTEGER NOT NULL CHECK(bracket_size IN (4,8,16,32)))"),
  d.prepare("CREATE TABLE IF NOT EXISTS parallel_slots (event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE, round INTEGER NOT NULL, position INTEGER NOT NULL, athlete TEXT NOT NULL, PRIMARY KEY(event_id,round,position))"),
  d.prepare("CREATE INDEX IF NOT EXISTS idx_events_live_date ON events(is_live,event_date)"),d.prepare("CREATE INDEX IF NOT EXISTS idx_results_event_points ON results(event_id,points DESC)"),d.prepare("CREATE INDEX IF NOT EXISTS idx_parallel_slots_event_round ON parallel_slots(event_id,round,position)")]);
  const count=await d.prepare("SELECT COUNT(*) count FROM events").all<{count:number}>();if((count.results[0]?.count??0)===0){for(const e of seed){await d.prepare("INSERT INTO events(id,title,category,location,event_date,is_live,next_start,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,e.title,e.category,e.location,e.eventDate,e.isLive?1:0,e.nextStart,e.updatedAt).run();for(const r of e.results)await d.prepare("INSERT INTO results(id,event_id,athlete,club,time,points,status) VALUES(?,?,?,?,?,?,?)").bind(r.id,e.id,r.athlete,r.club,r.time,r.points,r.status).run();}}return d;}
export async function getEvents():Promise<EventData[]>{const d=await ensureDb();if(!d)return seed;const es=await d.prepare("SELECT id,title,category,location,event_date eventDate,is_live isLive,next_start nextStart,updated_at updatedAt FROM events ORDER BY event_date DESC,id DESC").all<Omit<EventData,"results">>();const out:EventData[]=[];for(const e of es.results){const rs=await d.prepare("SELECT id,athlete,club,time,points,status FROM results WHERE event_id=? ORDER BY points DESC,time ASC").bind(e.id).all<Result>();const cfg=await d.prepare("SELECT bracket_size size FROM parallel_brackets WHERE event_id=?").bind(e.id).all<{size:number}>();let bracket:Bracket|undefined;if(cfg.results[0]){const slots=await d.prepare("SELECT round,position,athlete FROM parallel_slots WHERE event_id=? ORDER BY round,position").bind(e.id).all<BracketSlot>();bracket={size:cfg.results[0].size,slots:slots.results};}out.push({...e,results:rs.results,bracket});}return out;}
export async function addResult(i:{eventId:number;athlete:string;club:string;time:string;points:number}){const d=await ensureDb();if(!d)return;await d.prepare("INSERT INTO results(event_id,athlete,club,time,points,status) VALUES(?,?,?,?,?,'Finished')").bind(i.eventId,i.athlete,i.club,i.time,i.points).run();await touch(d,i.eventId);}
export async function addEvent(i:{title:string;category:string;location:string;eventDate:string;nextStart?:string;eventType?:string;bracketSize?:number}){const d=await ensureDb();if(!d)return;await d.prepare("UPDATE events SET is_live=0").run();const created=await d.prepare("INSERT INTO events(title,category,location,event_date,is_live,next_start,updated_at) VALUES(?,?,?,?,1,?,?)").bind(i.eventType==="parallel"?"Parallel":i.title,i.category,i.location,i.eventDate,i.nextStart||null,new Date().toISOString()).run();const id=Number(created.meta?.last_row_id);if(i.eventType==="parallel"&&[4,8,16,32].includes(Number(i.bracketSize)))await d.prepare("INSERT INTO parallel_brackets(event_id,bracket_size) VALUES(?,?)").bind(id,Number(i.bracketSize)).run();}
export async function seedBracket(eventId:number,names:string[]){const d=await ensureDb();if(!d)return;const cfg=await d.prepare("SELECT bracket_size size FROM parallel_brackets WHERE event_id=?").bind(eventId).all<{size:number}>();const size=cfg.results[0]?.size;if(!size)throw new Error("Parallel bracket not found");await d.prepare("DELETE FROM parallel_slots WHERE event_id=?").bind(eventId).run();const clean=names.map(x=>x.trim()).filter(Boolean).slice(0,size);const statements=Array.from({length:size},(_,position)=>d.prepare("INSERT INTO parallel_slots(event_id,round,position,athlete) VALUES(?,0,?,?)").bind(eventId,position,clean[position]||`TBD ${position+1}`));await d.batch(statements);await touch(d,eventId);}
export async function placeBracketSlot(eventId:number,targetRound:number,targetPosition:number,athlete:string){const d=await ensureDb();if(!d)return;const cfg=await d.prepare("SELECT bracket_size size FROM parallel_brackets WHERE event_id=?").bind(eventId).all<{size:number}>();const size=cfg.results[0]?.size||0;const maxRound=Math.log2(size);const maxPosition=size/2**targetRound;if(targetRound<1||targetRound>maxRound||targetPosition<0||targetPosition>=maxPosition)throw new Error("Invalid bracket position");await d.prepare("INSERT INTO parallel_slots(event_id,round,position,athlete) VALUES(?,?,?,?) ON CONFLICT(event_id,round,position) DO UPDATE SET athlete=excluded.athlete").bind(eventId,targetRound,targetPosition,athlete).run();await touch(d,eventId);}
async function touch(d:D1,id:number){await d.prepare("UPDATE events SET updated_at=? WHERE id=?").bind(new Date().toISOString(),id).run();}
export async function deleteResult(id:number){const d=await ensureDb();if(d)await d.prepare("DELETE FROM results WHERE id=?").bind(id).run();}
